language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-proyectowp' ]; then cd .. && eval "mv $currentfolder generator-proyectowp" && cd generator-proyectowp; fi
